# Generated by Django 5.2.15 on 2026-07-07 03:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Email Address')),
                ('password', models.CharField(max_length=128)),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='Staff Status')),
                ('is_admin', models.BooleanField(default=False, help_text='Designates whether the user has all permissions.', verbose_name='Admin Status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active.', verbose_name='Active Status')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='custom_user_set', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='custom_user_set', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ['-create_date_time'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, help_text='Unique API key for client authentication', max_length=255, null=True, unique=True, verbose_name='API Key')),
                ('base_url', models.URLField(help_text='Base URL of the client application', max_length=500, verbose_name='Base URL')),
                ('for_login', models.BooleanField(default=False, help_text='Designates whether this client is used for login', verbose_name='For Login')),
                ('for_payment', models.BooleanField(default=False, help_text='Designates whether this client is used for payment', verbose_name='For Payment')),
                ('name', models.CharField(blank=True, help_text='Name of the client application', max_length=255, null=True, verbose_name='Client Name')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this client is active', verbose_name='Is Active')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('user', models.ForeignKey(help_text='The user who owns this client', on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'db_table': 'client',
                'ordering': ['-create_date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'Login'), ('logout', 'Logout'), ('payment', 'Payment'), ('transfer', 'Transfer'), ('update', 'Update'), ('delete', 'Delete'), ('create', 'Create')], max_length=20, verbose_name='Action')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='Details')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'User Activity Log',
                'verbose_name_plural': 'User Activity Logs',
                'db_table': 'user_activity_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='users_is_acti_847b48_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='users_is_staf_9ea57e_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['user'], name='client_user_id_9787a2_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['base_url'], name='client_base_ur_4ed801_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['api_key'], name='client_api_key_274e4c_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['is_active'], name='client_is_acti_9a8432_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['for_login'], name='client_for_log_b321ca_idx'),
        ),
        migrations.AddIndex(
            model_name='client',
            index=models.Index(fields=['for_payment'], name='client_for_pay_8e1f02_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['user', 'action'], name='user_activi_user_id_2def1e_idx'),
        ),
        migrations.AddIndex(
            model_name='useractivitylog',
            index=models.Index(fields=['timestamp'], name='user_activi_timesta_7e2b74_idx'),
        ),
    ]
