# Generated by Django 5.2.15 on 2026-07-07 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='base_url',
            field=models.CharField(help_text='Base URL of the client application', max_length=500, verbose_name='Base URL'),
        ),
    ]
