# Generated by Django 5.2.15 on 2026-07-08 05:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('currency', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_currency', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Currency',
                'verbose_name_plural': 'Account Currencies',
                'db_table': 'account_currency',
            },
        ),
        migrations.CreateModel(
            name='AccountLanguage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('lang', models.CharField(max_length=10)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_language', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Language',
                'verbose_name_plural': 'Account Languages',
                'db_table': 'account_language',
            },
        ),
        migrations.CreateModel(
            name='AccountTimeZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('time_zone', models.CharField(max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account_time_zone', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Account Time Zone',
                'verbose_name_plural': 'Account Time Zones',
                'db_table': 'account_time_zone',
            },
        ),
        migrations.CreateModel(
            name='ProfileSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('bio', models.TextField(blank=True, default='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profile Settings',
                'verbose_name_plural': 'Profile Settings',
                'db_table': 'profile_settings',
            },
        ),
        migrations.CreateModel(
            name='Security2FA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('authenticator_app', models.BooleanField(default=False)),
                ('OTP', models.BooleanField(default=False)),
                ('B_T', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='security_2fa', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '2FA Security Settings',
                'verbose_name_plural': '2FA Security Settings',
                'db_table': 'security_2fa',
            },
        ),
        migrations.CreateModel(
            name='SettingsNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('email', models.BooleanField(default=True)),
                ('push', models.BooleanField(default=True)),
                ('marketing', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Settings',
                'verbose_name_plural': 'Notification Settings',
                'db_table': 'settings_notification',
            },
        ),
        migrations.CreateModel(
            name='SettingsPrivacy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('auth_2f', models.BooleanField(default=False)),
                ('data_sharing', models.BooleanField(default=False)),
                ('activity_status', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Privacy Settings',
                'verbose_name_plural': 'Privacy Settings',
                'db_table': 'settings_privacy',
            },
        ),
    ]
