# Generated by Django 5.2.15 on 2026-07-07 03:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USD', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='US Dollar')),
                ('EUR', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Euro')),
                ('JPY', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Japanese Yen')),
                ('GBP', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='British Pound')),
                ('preferred_currency', models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound')], default='USD', help_text="User's preferred currency for display", max_length=3, verbose_name='Preferred Currency')),
                ('is_active', models.BooleanField(default=True, help_text='Whether this wallet is active', verbose_name='Is Active')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('user', models.OneToOneField(help_text='The user who owns this wallet', on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'db_table': 'wallet',
                'ordering': ['-create_date_time'],
                'indexes': [models.Index(fields=['user'], name='wallet_user_id_504f58_idx'), models.Index(fields=['preferred_currency'], name='wallet_preferr_11ec20_idx'), models.Index(fields=['is_active'], name='wallet_is_acti_aa379e_idx')],
            },
        ),
    ]
