# Generated by Django 5.2.15 on 2026-07-08 08:39

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('USD', models.DecimalField(decimal_places=6, default=1.0, max_digits=15)),
                ('EUR', models.DecimalField(decimal_places=6, default=0.0, max_digits=15)),
                ('JPY', models.DecimalField(decimal_places=6, default=0.0, max_digits=15)),
                ('GBP', models.DecimalField(decimal_places=6, default=0.0, max_digits=15)),
            ],
            options={
                'verbose_name': 'Currency Price History',
                'verbose_name_plural': 'Currency Price History',
                'db_table': 'currency_price_history',
                'ordering': ['-create_date_time'],
            },
        ),
        migrations.CreateModel(
            name='UserCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('USD', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('EUR', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('JPY', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('GBP', models.DecimalField(decimal_places=2, default=0.0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_lmt', models.DecimalField(decimal_places=2, default=0.0, help_text='Maximum allowed balance/spend limit', max_digits=15, verbose_name='Maximum Limit')),
                ('use_lmt', models.DecimalField(decimal_places=2, default=0.0, help_text='Amount of the limit already used', max_digits=15, verbose_name='Used Limit')),
                ('payment_address', models.CharField(blank=True, default='', max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='currency_account', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Currency',
                'verbose_name_plural': 'User Currencies',
                'db_table': 'currency',
            },
        ),
        migrations.CreateModel(
            name='StandardCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('number', models.CharField(max_length=19)),
                ('cvc', models.CharField(max_length=4)),
                ('exp', models.CharField(help_text='Format: MM/YY', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('user_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='wallet.usercurrency')),
            ],
            options={
                'verbose_name': 'Standard Card',
                'verbose_name_plural': 'Standard Cards',
                'db_table': 'standard_cards',
            },
        ),
        migrations.CreateModel(
            name='PremiumCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('number', models.CharField(max_length=19)),
                ('cvc', models.CharField(max_length=4)),
                ('exp', models.CharField(help_text='Format: MM/YY', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('user_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='wallet.usercurrency')),
            ],
            options={
                'verbose_name': 'Premium Card',
                'verbose_name_plural': 'Premium Cards',
                'db_table': 'premium_cards',
            },
        ),
        migrations.CreateModel(
            name='VirtualCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('number', models.CharField(max_length=19)),
                ('cvc', models.CharField(max_length=4)),
                ('exp', models.CharField(help_text='Format: MM/YY', max_length=5)),
                ('is_active', models.BooleanField(default=True)),
                ('user_currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)ss', to='wallet.usercurrency')),
            ],
            options={
                'verbose_name': 'Virtual Card',
                'verbose_name_plural': 'Virtual Cards',
                'db_table': 'virtual_cards',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date_time', models.DateTimeField(auto_now_add=True, verbose_name='Date Created')),
                ('update_date_time', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('entity', models.CharField(max_length=255)),
                ('transaction_date', models.DateTimeField()),
                ('method', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-transaction_date'],
                'indexes': [models.Index(fields=['user'], name='transaction_user_id_b5bcfd_idx'), models.Index(fields=['status'], name='transaction_status_505a2f_idx'), models.Index(fields=['transaction_date'], name='transaction_transac_0d716a_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='usercurrency',
            index=models.Index(fields=['user'], name='currency_user_id_20c921_idx'),
        ),
    ]
