# Generated by Django 5.2.15 on 2026-07-08 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_currencypricehistory_usercurrency_standardcard_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrency',
            name='payment_address',
            field=models.CharField(blank=True, editable=False, help_text='Auto-generated on creation, e.g. CH-WAL-9082-1422-9841', max_length=255, unique=True, verbose_name='Payment Address'),
        ),
    ]
