# Generated by Django 5.2.15 on 2026-07-08 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0003_alter_usercurrency_payment_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrency',
            name='payment_address',
            field=models.CharField(blank=True, editable=False, max_length=255, unique=True, verbose_name='Payment Address'),
        ),
    ]
